<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Haven.DotNet</PackageId>
        <Authors>Josh Solanes</Authors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <!-- Uncomment for debugging, to enable stepping into the library
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <DebugType>embedded</DebugType>
        -->
    </PropertyGroup>
    
</Project>
